version: "3.8"
name: 'mvc-framework'
services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: 
      context: ./configs
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html:delegated
  mysql:
    build:
      context: ./configs
      dockerfile: mysql.dockerfile
    container_name: mvcframework-mysql-1
    env_file:
      - ./env/mysql.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

 # npm:

